"""empty message

Revision ID: 028c8eda7a36
Revises: a83aaa65c9bd
Create Date: 2025-08-09 15:43:56.476439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028c8eda7a36'
down_revision = 'a83aaa65c9bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_unit_laundry', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('owner_occupancy', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('open_floorplan', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fireplace', sa.Integer(), nullable=True))
        batch_op.drop_column('open_layout')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open_layout', sa.INTEGER(), nullable=True))
        batch_op.drop_column('fireplace')
        batch_op.drop_column('open_floorplan')
        batch_op.drop_column('owner_occupancy')
        batch_op.drop_column('in_unit_laundry')

    # ### end Alembic commands ###
