"""empty message

Revision ID: 259bdf062b64
Revises: 0f02b7033cf6
Create Date: 2025-08-10 13:51:06.272301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259bdf062b64'
down_revision = '0f02b7033cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
