"""empty message

Revision ID: 3d720ab74139
Revises: 636d1985dc39
Create Date: 2025-08-11 18:23:24.415903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d720ab74139'
down_revision = '636d1985dc39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('property_taxes')
        batch_op.drop_column('price')
        batch_op.drop_column('monthly_assessments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_assessments', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('property_taxes', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
