"""initial migration

Revision ID: 588cc53da985
Revises: 
Create Date: 2025-08-12 09:53:18.236325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588cc53da985'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('list_price', sa.Integer(), nullable=True),
    sa.Column('total_monthly_payment', sa.Integer(), nullable=True),
    sa.Column('monthly_hoa', sa.Integer(), nullable=True),
    sa.Column('annual_property_tax', sa.Integer(), nullable=True),
    sa.Column('cost_score', sa.Integer(), nullable=True),
    sa.Column('av_score', sa.Integer(), nullable=True),
    sa.Column('brick_building', sa.Boolean(), nullable=True),
    sa.Column('garden_unit', sa.Boolean(), nullable=True),
    sa.Column('parking', sa.Integer(), nullable=True),
    sa.Column('in_unit_laundry', sa.Integer(), nullable=True),
    sa.Column('top_floor', sa.Boolean(), nullable=True),
    sa.Column('busy_street', sa.Integer(), nullable=True),
    sa.Column('hvac', sa.Integer(), nullable=True),
    sa.Column('owner_occupancy', sa.Integer(), nullable=True),
    sa.Column('overall_size', sa.Integer(), nullable=True),
    sa.Column('train', sa.Integer(), nullable=True),
    sa.Column('grocery_store', sa.Integer(), nullable=True),
    sa.Column('gym', sa.Integer(), nullable=True),
    sa.Column('park', sa.Integer(), nullable=True),
    sa.Column('lake', sa.Integer(), nullable=True),
    sa.Column('hoa_funding', sa.Integer(), nullable=True),
    sa.Column('special_assessments', sa.Integer(), nullable=True),
    sa.Column('windows', sa.Integer(), nullable=True),
    sa.Column('walls', sa.Integer(), nullable=True),
    sa.Column('office_space', sa.Integer(), nullable=True),
    sa.Column('flooring', sa.Integer(), nullable=True),
    sa.Column('carpet', sa.Integer(), nullable=True),
    sa.Column('natural_light', sa.Integer(), nullable=True),
    sa.Column('open_floorplan', sa.Integer(), nullable=True),
    sa.Column('dining_room', sa.Integer(), nullable=True),
    sa.Column('balcony', sa.Integer(), nullable=True),
    sa.Column('outdoor_space', sa.Integer(), nullable=True),
    sa.Column('rooftop', sa.Integer(), nullable=True),
    sa.Column('nooks', sa.Integer(), nullable=True),
    sa.Column('fireplace', sa.Integer(), nullable=True),
    sa.Column('microwave', sa.Boolean(), nullable=True),
    sa.Column('wine_cooler', sa.Boolean(), nullable=True),
    sa.Column('kitchen_cabinets', sa.Integer(), nullable=True),
    sa.Column('kitchen_counters', sa.Integer(), nullable=True),
    sa.Column('bartop', sa.Integer(), nullable=True),
    sa.Column('kitchen_sink', sa.Integer(), nullable=True),
    sa.Column('stove', sa.Integer(), nullable=True),
    sa.Column('island', sa.Integer(), nullable=True),
    sa.Column('en_suite_bathroom', sa.Boolean(), nullable=True),
    sa.Column('bathroom_showers', sa.Integer(), nullable=True),
    sa.Column('bathroom_vanities', sa.Integer(), nullable=True),
    sa.Column('master_bathroom', sa.Integer(), nullable=True),
    sa.Column('master_vanity', sa.Integer(), nullable=True),
    sa.Column('master_closet', sa.Integer(), nullable=True),
    sa.Column('master_bedroom', sa.Integer(), nullable=True),
    sa.Column('closets', sa.Integer(), nullable=True),
    sa.Column('cabinet_storage', sa.Integer(), nullable=True),
    sa.Column('storage_unit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('user')
    op.drop_table('listing')
    # ### end Alembic commands ###
