"""empty message

Revision ID: 636d1985dc39
Revises: a09669991e75
Create Date: 2025-08-10 19:07:29.738701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636d1985dc39'
down_revision = 'a09669991e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('av_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('av_score')
        batch_op.drop_column('cost_score')

    # ### end Alembic commands ###
