"""empty message

Revision ID: a09669991e75
Revises: 259bdf062b64
Create Date: 2025-08-10 14:57:53.816476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09669991e75'
down_revision = '259bdf062b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_monthly_payment', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monthly_hoa', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('annual_property_tax', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('annual_property_tax')
        batch_op.drop_column('monthly_hoa')
        batch_op.drop_column('total_monthly_payment')

    # ### end Alembic commands ###
