"""empty message

Revision ID: a83aaa65c9bd
Revises: d6cbcb63f17f
Create Date: 2025-08-09 11:57:21.252580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a83aaa65c9bd'
down_revision = 'd6cbcb63f17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('garden_unit', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('train', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grocery_store', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gym', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('park', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lake', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('closets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cabinet_storage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('storage_unit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('natural_light', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nooks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('open_layout', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('balcony', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('outdoor_space', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rooftop', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dining_room', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('overall_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monthly_assessments', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hoa_funding', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('special_assessments', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('property_taxes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bartop', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kitchen_sink', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wine_cooler', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stove', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('island', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('microwave', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('master_closet', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('master_bedroom', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('list_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('master_bathroom', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('master_vanity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('en_suite_bathroom', sa.Boolean(), nullable=True))
        batch_op.alter_column('parking',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('not_garden_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('not_garden_unit', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('parking',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.drop_column('en_suite_bathroom')
        batch_op.drop_column('master_vanity')
        batch_op.drop_column('master_bathroom')
        batch_op.drop_column('list_price')
        batch_op.drop_column('master_bedroom')
        batch_op.drop_column('master_closet')
        batch_op.drop_column('microwave')
        batch_op.drop_column('island')
        batch_op.drop_column('stove')
        batch_op.drop_column('wine_cooler')
        batch_op.drop_column('kitchen_sink')
        batch_op.drop_column('bartop')
        batch_op.drop_column('property_taxes')
        batch_op.drop_column('special_assessments')
        batch_op.drop_column('hoa_funding')
        batch_op.drop_column('monthly_assessments')
        batch_op.drop_column('overall_size')
        batch_op.drop_column('dining_room')
        batch_op.drop_column('rooftop')
        batch_op.drop_column('outdoor_space')
        batch_op.drop_column('balcony')
        batch_op.drop_column('open_layout')
        batch_op.drop_column('nooks')
        batch_op.drop_column('natural_light')
        batch_op.drop_column('storage_unit')
        batch_op.drop_column('cabinet_storage')
        batch_op.drop_column('closets')
        batch_op.drop_column('lake')
        batch_op.drop_column('park')
        batch_op.drop_column('gym')
        batch_op.drop_column('grocery_store')
        batch_op.drop_column('train')
        batch_op.drop_column('garden_unit')

    # ### end Alembic commands ###
