"""empty message

Revision ID: d6cbcb63f17f
Revises: 
Create Date: 2025-08-08 14:29:01.472710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6cbcb63f17f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brick_building', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('parking', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('not_garden_unit', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('top_floor', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('busy_street', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('windows', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('walls', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('office_space', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kitchen_cabinets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kitchen_counters', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('flooring', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('carpet', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bathroom_showers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bathroom_vanities', sa.Integer(), nullable=True))
        batch_op.drop_column('bathrooms')
        batch_op.drop_column('kitchen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kitchen', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('bathrooms', sa.INTEGER(), nullable=True))
        batch_op.drop_column('bathroom_vanities')
        batch_op.drop_column('bathroom_showers')
        batch_op.drop_column('carpet')
        batch_op.drop_column('flooring')
        batch_op.drop_column('kitchen_counters')
        batch_op.drop_column('kitchen_cabinets')
        batch_op.drop_column('office_space')
        batch_op.drop_column('walls')
        batch_op.drop_column('windows')
        batch_op.drop_column('busy_street')
        batch_op.drop_column('top_floor')
        batch_op.drop_column('not_garden_unit')
        batch_op.drop_column('parking')
        batch_op.drop_column('brick_building')

    # ### end Alembic commands ###
